[build]

    publish = 'www'

[[headers]]

    for = '/*'

    [headers.values]

        Strict-Transport-Security = 'max-age=63072000; preload'
        Content-Security-Policy = "default-src 'self'; script-src 'self' www.googletagmanager.com www.google-analytics.com; img-src 'self' www.googletagmanager.com www.google-analytics.com; object-src 'none'"
        X-Content-Type-Options = 'nosniff'
        X-Frame-Options = 'DENY'
        X-XSS-Protection = '1; mode=block'

[[redirects]]

    from = "https://goofy-yalow-a44a3c.netlify.com/*"
    to = "https://olympics.jkarahalis.com/:splat"
    status = 301
    force = true
